server:
  port: 9500
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

#datasource Configuration
spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kwaresch?currentSchema=kware
    username: postgres
    password: root

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
      enabled: true

file:
  upload:
    location: D:/data/upload
    webPath: /attach
    maxSize: 20971520
    ext: jpg, jpeg, gif, png, bmp, txt, zip, hwp*, doc*, ppt*, xls*, mp4, mkv, avi, mpg, flv, wmv, mov, pdf, egg

logging:
  config: classpath:log4j2.yml

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui/index.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**
